version: '3'


services:
    web:
        depends_on: 
            - db
        image: retarf/django
        volumes: 
            - ./code:/code
        ports:
            - "80:8000"
        command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        deploy:
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.hostname == draco
    db:
        image: postgres
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: mypass
            POSTGRES_DB: tproject
        deploy:
            placement:
                constraints:
                    - node.hostname == pentagon
